image: node:16.14.0

variables:
  DEVELOP_BRANCH: "develop"
  PROD_BRANCH: "prod"
  APP_API: "vokit-api"
  APP_CORE: "vokit_core"
  DEVELOP_WEBHOOK_URL: $CI_DEVELOP_WEBHOOK_URL
  PROD_WEBHOOK_URL: $CI_PROD_WEBHOOK_URL

.base-rules:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - when: manual
      allow_failure: true
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

stages:
  - cache-install
  - build-core
  - lint
  - build
  - publish
  - deploy

default:
  before_script:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - pnpm config set store-dir .pnpm-store

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store
    - node_modules/
    - "packages/**/node_modules/"
    - "apps/**/node_modules/"
    - "packages/$APP_CORE/dist/"
    - "apps/api-vokit/dist/"
    - "apps/**/dist/"
    - "packages/**/dist/"

# Apps
.api:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "apps/api-vokit/**/*"

.core:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "packages/$APP_CORE/**/*"

.prod-develop:
  rules:
    - if: $CI_COMMIT_BRANCH == $DEVELOP_BRANCH || $CI_COMMIT_BRANCH == $PROD_BRANCH
      when: always

# Steps
cache-install:
  stage: cache-install
  extends: .base-rules
  script:
    - echo "Installing dependencies..."
    - pnpm -r install --frozen-lockfile

lint-api:
  stage: lint
  extends:
    - .api
  needs: ["cache-install"]
  script:
    - echo "Checking the api lint..."
    - pnpm --filter $APP_API lint:check

lint-core:
  stage: lint
  extends:
    - .core
  needs: ["cache-install"]
  script:
    - echo "Checking the core lint..."
    - pnpm --filter $APP_CORE lint:check

build-core:
  stage: build-core
  extends:
    - .core
  needs: ["cache-install"]
  script:
    - echo "Compiling the core code..."
    - pnpm --filter $APP_CORE build

build-api:
  stage: build
  extends:
    - .api
  needs: ["build-core"]
  script:
    - echo "Compiling the api code..."
    - pnpm --filter $APP_API build
    - echo "starting the api in ci mode..."
    - pnpm --filter $APP_API start:ci

publish-api:
  image: docker:latest
  stage: publish
  extends:
    - .api
    - .prod-develop
  needs: ["build-api"]
  services:
    - name: docker:dind
  before_script:
    - ""
  script:
    - |-
      if [ $CI_COMMIT_BRANCH == $PROD_BRANCH ]; then REGISTRY_PATH="$CI_REGISTRY_IMAGE/prod/api"; else REGISTRY_PATH="$CI_REGISTRY_IMAGE/develop/api"; fi
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - echo "Creating the API Docker image..."
    - docker build -f "./apps/api-vokit/Dockerfile" --pull
      --cache-from "$REGISTRY_PATH:latest"
      --label "org.opencontainers.image.title=$CI_PROJECT_TITLE"
      --label "org.opencontainers.image.url=$CI_PROJECT_URL"
      --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT"
      --label "org.opencontainers.image.revision=$CI_COMMIT_SHA"
      --label "org.opencontainers.image.version=$CI_COMMIT_REF_NAME" -t "$REGISTRY_PATH" .
    - echo "Publishing the API Docker image to GitLab Container Registry..."
    - docker push "$REGISTRY_PATH"

deploy:
  stage: deploy
  cache: []
  before_script:
    - ""
  extends: 
    - .prod-develop
  variables:
    GIT_STRATEGY: none
  script:
    - |-
        if [ $CI_COMMIT_BRANCH == $PROD_BRANCH ]; then DEPLOY_URL="$PROD_WEBHOOK_URL"; else DEPLOY_URL="$DEVELOP_WEBHOOK_URL"; fi
    - |-
        DEPLOY_CURL_COMMAND='curl -X POST -H "Content-Type: application/json" $DEPLOY_URL'
    - echo "Deploying API"
    - echo $DEPLOY_CURL_COMMAND
    - 'eval "$DEPLOY_CURL_COMMAND"'
