export enum CardTypeEnum {
  GRASS = 1,
  FIRE = 2,
  WATER = 3,
  ELECTRIC = 4,
  FIGHTING = 5,
  PSYCHIC = 6,
  COLORLESS = 7,
  DARK = 8,
  DARKNESS = 8,
  STEEL = 9,
  METAL = 9,
  DRAGON = 10,
  FAIRY = 11,
  NONE = 12,
}

export enum CardTypeEnumFrench {
  'Plante' = 1,
  'Feu' = 2,
  'Eau' = 3,
  'Électrique' = 4,
  'Combat' = 5,
  'Psy' = 6,
  'Incolore' = 7,
  'Ténèbres' = 8,
  'Acier' = 9,
  'Dragon' = 10,
  'Fée' = 11,
  'Aucun' = 12,
}
