import { StoreType } from "../../local-core/context";
import React from "react";

export default React.createContext<StoreType>({
  series: null,
  cardSetFilter: null,
  setCardSetFilter: () => {},
  nameFilter: "",
  setNameFilter: () => {},
  resetAllFilters: () => {},
  rarityFilter: [],
  setRarityFilter: () => {},
  order: "",
  setOrder: () => {},
  collectionMode: false,
  setCollectionMode: () => {},
  separateReverse: false,
  setSeparateReverse: () => {},
  possessionFilter: null,
  setPossessionFilter: () => {},
  cards: [],
  setCards: () => {},
  showOptionCards: false,
  setShowOptionCards: () => {},
  page: 1,
  setPage: () => {},
  pagination: null,
  setPagination: () => {},
  massInput: false,
  setMassInput: () => {},
  user: {
    id: "",
    role: 0,
    shownName: "",
  },
  setUser: () => {},
  notifications: [],
  setNotifications: () => {},
  tags: null,
  setTags: () => {},
  listDisplay: false,
  setListDisplay: () => {}
});
