version: '3.3'

services:
  postgres:
    restart: unless-stopped
    image: postgres:latest
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: WWxX26SVWhr29
      POSTGRES_DB: pokecard
      PGDATA: /var/lib/postgresql/data
    volumes:
      - data-postgres:/var/lib/postgresql/data

  pgadmin:
    restart: unless-stopped
    container_name: "pgadmin"
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: email@example.com
      PGADMIN_DEFAULT_PASSWORD: wW2NxDq57unyUz
    volumes:
      - data-pgadmin:/var/lib/pgadmin

  # abyss-crypt-back:
  #   build: .
  #   restart: always
  #   working_dir: /home/node/app
  #   image: node:16.14.0-alpine
  #   container_name: abyss-crypt-back
  #   command: npm run prod
  #   ports:
  #     - "10101:10101"
  #   depends_on:
  #     - postgres

volumes:
  data-postgres:
  data-pgadmin:
